### ISSUE TITLE
migrate to astro

### ISSUE THREAD

**Issue by riderx** [riderx/captime-website#47]
we have many issue in nuxt so the goal is to migrate to stop this mess

**Comment by rishi-raj-jain** [comment]
@riderx Do you want it to be like how I did the other one? Anything I should know to keep in mind?

**Comment by riderx** [comment]
same :)

**Comment by rishi-raj-jain** [comment]
On it!

**Comment by riderx** [comment]
i also made the issue here for doc: https://github.com/Cap-go/capgo/issues/262

**Comment by riderx** [comment]
No problem take your time :)

**Comment by Atinux** [comment]
Happy to give me some hints about the issue about the mess?

**Comment by riderx** [comment]
Sorry @Atinux i tried, I even tagged you on Nuxt content repo said I’m willing to pay to make it fix.

It has been 3 weeks since my blog was broken after a minor update.
Posted here:
https://github.com/nuxt/content/issues/2185
and
https://github.com/nuxt/content/issues/2128

So I create 2 tasks this week to get out of issues.

This one for Capgo: https://github.com/Cap-go/capgo/issues/261
And the one here for Captime.

Basically, I lost all my SEO effort, for 2 website for 3 weeks, just with auto merge fix update.

And I tried to revert it and couldn't even find a proper way to revert...
I really Like Nuxt but sometimes the "magic" of it make it a black box and without the Nuxt team help I couldn't get myself out of trouble.

So now my both websites left Nuxt for Astro, it seems a simpler approach for static website and my needs.

I was thinking to make my webapps with Nuxt but now I'm more thinking to keep using Vitesse who is also a simpler approach I can debug myself.

I really believe in Nuxt, but right now it seems not fitting my need of indie maker
